# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c71e171d153fd5bbc7d33b3959ff635e"
name = "True North Payments"
application_url = "https://digital.tnpsettle.com/shopify/settings?brandKey=tnp"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
