/**
 * Shopify CLI Helper Library
 * Executes Shopify CLI commands programmatically for app deployment
 * 
 * Requirements:
 * - SHOPIFY_CLI_PARTNERS_TOKEN: Partner API token for CLI authentication
 * - SHOPIFY_ORG_ID: Shopify Partners organization ID
 * - Node.js environment with access to child_process
 */

import { spawn, exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

const execAsync = promisify(exec);

export interface ShopifyAppConfig {
  name: string;
  brandKey: string;
  clientId?: string;
  applicationUrl: string;
  embedded: boolean;
  redirectUrls: string[];
  scopes: string[];
  supportUrl?: string;
  privacyUrl?: string;
  termsUrl?: string;
  partnersToken?: string;
  orgId?: string;
  extension?: {
    enabled: boolean;
    buttonLabel: string;
    minTotal: number;
    currency: string;
    palette: { primary: string; accent: string };
  };
}

export interface DeployResult {
  success: boolean;
  appId?: string;
  clientId?: string;
  appUrl?: string;
  error?: string;
  logs: string[];
}

let _resolvedCmd: string | null = null;

export async function getShopifyCommand(): Promise<string> {
  if (_resolvedCmd) return _resolvedCmd;
  try {
    await execAsync("shopify version");
    _resolvedCmd = "shopify";
    return _resolvedCmd;
  } catch {
    try {
      await execAsync("npx -y shopify version");
      _resolvedCmd = "npx -y shopify";
      return _resolvedCmd;
    } catch {
      _resolvedCmd = "shopify";
      return _resolvedCmd;
    }
  }
}

/**
 * Check if Shopify CLI is installed
 */
export async function isShopifyCliInstalled(): Promise<boolean> {
  try {
    const cmd = await getShopifyCommand();
    await execAsync(`${cmd} version`);
    return true;
  } catch {
    return false;
  }
}

/**
 * Get Shopify CLI version
 */
export async function getShopifyCliVersion(): Promise<string | null> {
  try {
    const cmd = await getShopifyCommand();
    const { stdout } = await execAsync(`${cmd} version`);
    return stdout.trim();
  } catch {
    return null;
  }
}

/**
 * Generate shopify.app.toml content
 */
export function generateAppToml(config: ShopifyAppConfig): string {
  const redirectUrlsStr = config.redirectUrls.map(u => `"${u}"`).join(", ");
  const scopesStr = config.scopes.join(", ");

  return `# Shopify App Configuration
# Generated by PortalPay Plugin Studio
# Brand: ${config.brandKey}

name = "${config.name}"
client_id = "${config.clientId || ""}"
application_url = "${config.applicationUrl}"
embedded = ${config.embedded}

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "${scopesStr}"

[auth]
redirect_urls = [
  ${redirectUrlsStr}
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

${config.supportUrl || config.privacyUrl || config.termsUrl ? `[app_proxy]
# URL configuration for app proxy
${config.supportUrl ? `# Support: ${config.supportUrl}` : ""}
${config.privacyUrl ? `# Privacy: ${config.privacyUrl}` : ""}
${config.termsUrl ? `# Terms: ${config.termsUrl}` : ""}` : ""}
`;
}

export function generateExtensionToml(config: ShopifyAppConfig): string {
  if (!config.extension?.enabled) {
    return "";
  }

  return `# Checkout UI Extension Configuration
# Generated by PortalPay Plugin Studio

api_version = "2024-10"

[[extensions]]
name = "${config.name} - Crypto Payments"
handle = "${config.brandKey}-crypto-payment"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.payment-method-list.render-after"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "button_label"
type = "single_line_text_field"
name = "Button Label"
description = "Text displayed on the payment button"

[[extensions.settings.fields]]
key = "min_total"
type = "number_integer"
name = "Minimum Order Total"
description = "Minimum order total required to show crypto payment option"

[[extensions.settings.fields]]
key = "api_key"
type = "single_line_text_field"
name = "PortalPay API Key"
description = "Your PortalPay API Key (pk_live_...)"

[[extensions.settings.fields]]
key = "api_url"
type = "single_line_text_field"
name = "PortalPay API URL"
description = "Optional custom PortalPay API URL (e.g. for testing on localhost)"
`;
}

/**
 * Generate checkout extension source code
 */
export function generateCheckoutExtensionCode(config: ShopifyAppConfig): string {
  const ext = config.extension;
  if (!ext?.enabled) return "";

  return `import React from "react";
import {
  reactExtension,
  Banner,
  Button,
  useCartLines,
  useApi,
  useSettings,
} from "@shopify/ui-extensions-react/checkout";

export default reactExtension(
  "purchase.checkout.payment-method-list.render-after",
  () => <CryptoPaymentOption />
);

function CryptoPaymentOption() {
  const { extension } = useApi();
  const settings = useSettings();
  const cartLines = useCartLines();
  
  const buttonLabel = settings.button_label ?? "${ext.buttonLabel}";
  const minTotal = settings.min_total ?? ${ext.minTotal};
  const apiKey = settings.api_key ?? "";
  const apiUrl = settings.api_url ?? "${config.applicationUrl}";
  
  // Calculate cart total
  const cartTotal = cartLines.reduce((sum, line) => {
    return sum + (Number(line.cost?.totalAmount?.amount) || 0);
  }, 0);
  
  // Don't show if below minimum
  if (cartTotal < minTotal) {
    return null;
  }

  const handleCryptoPayment = async () => {
    let token = "";
    try {
      token = await extension.sessionToken.get();
    } catch (err) {
      console.error("Failed to get session token:", err);
    }
    const paymentUrl = \`\${apiUrl}/api/payments/crypto?session=\${token}&apiKey=\${apiKey}\`;
    window.open(paymentUrl, '_blank');
  };

  return (
    <Banner
      status="info"
      title="Pay with Cryptocurrency"
    >
      <Button
        kind="primary"
        appearance="monochrome"
        onPress={handleCryptoPayment}
        accessibilityLabel={buttonLabel}
        disabled={!apiKey}
      >
        {apiKey ? buttonLabel : "Please configure PortalPay API Key"}
      </Button>
    </Banner>
  );
}
`;
}

/**
 * Generate package.json for the extension
 */
export function generateExtensionPackageJson(config: ShopifyAppConfig): string {
  return JSON.stringify({
    name: `${config.brandKey}-shopify-extension`,
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "shopify app dev",
      build: "shopify app build",
      deploy: "shopify app deploy"
    },
    dependencies: {
      "@shopify/ui-extensions-react": "^2024.4.0",
      "react": "^18.2.0"
    },
    devDependencies: {
      "@shopify/cli": "^3.0.0",
      "typescript": "^5.0.0"
    }
  }, null, 2);
}

/**
 * Create a temporary Shopify app project directory
 */
export async function createAppProject(config: ShopifyAppConfig): Promise<string> {
  const rootDir = os.tmpdir();
  const tmpDir = path.join(rootDir, `.shopify-deploy-${config.brandKey}-${Date.now()}`);

  await fs.mkdir(tmpDir, { recursive: true });

  // Create junctions to main node_modules to make dependencies immediately available
  try {
    const workspaceRoot = process.cwd();
    const targetNodeModules = path.join(workspaceRoot, "node_modules");
    await fs.symlink(targetNodeModules, path.join(tmpDir, "node_modules"), "junction");

    // Also link node_modules directly inside the extension folder to satisfy local compiler resolution
    const extDir = path.join(tmpDir, "extensions", "checkout-ui");
    await fs.mkdir(extDir, { recursive: true });
    await fs.symlink(targetNodeModules, path.join(extDir, "node_modules"), "junction");
  } catch (err: any) {
    // Ignore symlink errors, fall back to default resolution
  }

  await fs.mkdir(path.join(tmpDir, "extensions", "checkout-ui", "src"), { recursive: true });

  // Write app.toml
  await fs.writeFile(
    path.join(tmpDir, "shopify.app.toml"),
    generateAppToml(config)
  );

  // Write package.json
  await fs.writeFile(
    path.join(tmpDir, "package.json"),
    generateExtensionPackageJson(config)
  );

  // Write extension config if enabled
  if (config.extension?.enabled) {
    await fs.writeFile(
      path.join(tmpDir, "extensions", "checkout-ui", "shopify.extension.toml"),
      generateExtensionToml(config)
    );

    await fs.writeFile(
      path.join(tmpDir, "extensions", "checkout-ui", "src", "Checkout.tsx"),
      generateCheckoutExtensionCode(config)
    );

    // Extension package.json
    await fs.writeFile(
      path.join(tmpDir, "extensions", "checkout-ui", "package.json"),
      JSON.stringify({
        name: `${config.brandKey}-checkout-ui`,
        version: "1.0.0",
        private: true,
        dependencies: {
          "@shopify/ui-extensions-react": "^2024.4.0",
          "react": "^18.2.0"
        }
      }, null, 2)
    );
  }

  return tmpDir;
}

/**
 * Run Shopify CLI command
 */
export async function runShopifyCommand(
  cwd: string,
  args: string[],
  env?: Record<string, string>,
  onLog?: (line: string) => void
): Promise<{ success: boolean; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const logs: string[] = [];
    let stdout = "";
    let stderr = "";

    const cmd = _resolvedCmd || "shopify";
    const proc = spawn(cmd, args, {
      cwd,
      env: {
        ...process.env,
        ...env,
        // Disable interactive mode
        CI: "true",
        SHOPIFY_FLAG_NO_PROMPT: "true",
      },
      shell: true,
    });

    proc.stdin?.end();

    proc.stdout.on("data", (data) => {
      const str = data.toString();
      stdout += str;
      logs.push(str);
      if (onLog) {
        str.split("\n").forEach((line: string) => {
          if (line.trim()) onLog(line.trim());
        });
      }
    });

    proc.stderr.on("data", (data) => {
      const str = data.toString();
      stderr += str;
      logs.push(`[stderr] ${str}`);
      if (onLog) {
        str.split("\n").forEach((line: string) => {
          if (line.trim()) onLog(`[stderr] ${line.trim()}`);
        });
      }
    });

    proc.on("close", (code) => {
      resolve({
        success: code === 0,
        stdout,
        stderr,
      });
    });

    proc.on("error", (err) => {
      resolve({
        success: false,
        stdout,
        stderr: err.message,
      });
    });
  });
}

/**
 * Deploy a Shopify app using the CLI
 */
export async function deployShopifyApp(
  config: ShopifyAppConfig,
  onLog?: (line: string) => void
): Promise<DeployResult> {
  const logs: string[] = [];

  const partnersToken = config.partnersToken || "";
  const orgId = config.orgId || "";

  if (!partnersToken) {
    return {
      success: false,
      error: "SHOPIFY_CLI_PARTNERS_TOKEN not configured",
      logs: ["Missing SHOPIFY_CLI_PARTNERS_TOKEN environment variable or cliPartnersToken in Plugin settings"],
    };
  }

  // Check if CLI is installed
  const cliInstalled = await isShopifyCliInstalled();
  if (!cliInstalled) {
    return {
      success: false,
      error: "Shopify CLI not installed",
      logs: ["Shopify CLI not found. Install with: npm install -g @shopify/cli"],
    };
  }

  if (!config.clientId) {
    return {
      success: false,
      error: "Client ID not configured",
      logs: ["Missing Shopify Client ID (API Key). Go to your app settings on the Shopify Partners Dashboard, copy the API key, and configure it under Publish settings first."],
    };
  }

  logs.push(`Starting deployment for ${config.name}...`);

  // Create project directory
  let projectDir: string;
  try {
    projectDir = await createAppProject(config);
    logs.push(`Created project directory: ${projectDir}`);
  } catch (e: any) {
    return {
      success: false,
      error: `Failed to create project: ${e.message}`,
      logs,
    };
  }

  const env: Record<string, string> = {};
  if (partnersToken.startsWith("atkn_")) {
    env.SHOPIFY_APP_AUTOMATION_TOKEN = partnersToken;
  } else {
    env.SHOPIFY_CLI_PARTNERS_TOKEN = partnersToken;
  }
  if (orgId) {
    env.SHOPIFY_CLI_ORGANIZATION_ID = orgId;
  }

  try {
    // Step 2: Deploy the app
    logs.push("Deploying app...");
    if (onLog) onLog("Deploying app...");
    const deployResult = await runShopifyCommand(
      projectDir,
      ["app", "deploy", "--allow-updates"],
      env,
      onLog
    );

    if (deployResult.stdout) logs.push(deployResult.stdout);
    if (deployResult.stderr) logs.push(`[stderr] ${deployResult.stderr}`);

    if (!deployResult.success) {
      return {
        success: false,
        error: "Deployment failed",
        logs,
      };
    }

    // Try to extract app info from output
    let appId: string | undefined;
    let clientId: string | undefined;
    let appUrl: string | undefined;

    const outputText = deployResult.stdout + deployResult.stderr;

    // Parse app ID from output
    const appIdMatch = outputText.match(/app[_\s-]?id[:\s]+([a-zA-Z0-9]+)/i);
    if (appIdMatch) appId = appIdMatch[1];

    const clientIdMatch = outputText.match(/client[_\s-]?id[:\s]+([a-zA-Z0-9]+)/i);
    if (clientIdMatch) clientId = clientIdMatch[1];

    const urlMatch = outputText.match(/https:\/\/partners\.shopify\.com\/[^\s]+/);
    if (urlMatch) appUrl = urlMatch[0];

    // Cleanup temp directory
    try {
      await fs.rm(projectDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }

    return {
      success: true,
      appId,
      clientId,
      appUrl,
      logs,
    };
  } catch (e: any) {
    logs.push(`Error: ${e.message}`);

    // Cleanup temp directory
    try {
      await fs.rm(projectDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }

    return {
      success: false,
      error: e.message,
      logs,
    };
  }
}

/**
 * Get app info from Shopify Partners
 */
export async function getAppInfo(clientId: string): Promise<any> {
  const partnersToken = process.env.SHOPIFY_CLI_PARTNERS_TOKEN;
  const orgId = process.env.SHOPIFY_ORG_ID;

  if (!partnersToken || !orgId) {
    return null;
  }

  try {
    const tmpDir = path.join(os.tmpdir(), `shopify-info-${Date.now()}`);
    await fs.mkdir(tmpDir, { recursive: true });

    // Create minimal config
    await fs.writeFile(
      path.join(tmpDir, "shopify.app.toml"),
      `client_id = "${clientId}"\nname = "temp"`
    );

    const result = await runShopifyCommand(
      tmpDir,
      ["app", "info"],
      {
        SHOPIFY_CLI_PARTNERS_TOKEN: partnersToken,
        SHOPIFY_CLI_ORGANIZATION_ID: orgId,
      }
    );

    await fs.rm(tmpDir, { recursive: true, force: true });

    return {
      success: result.success,
      output: result.stdout,
    };
  } catch {
    return null;
  }
}
