export interface CountrySubdivision {
  code: string;
  name: string;
}

export const COUNTRY_SUBDIVISIONS: Record<string, CountrySubdivision[]> = {
  // United States (50 States + DC + PR)
  US: [
    { code: "AL", name: "Alabama" },
    { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" },
    { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },
    { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" },
    { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" },
    { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" },
    { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" },
    { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" },
    { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" },
    { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" },
    { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" },
    { code: "WY", name: "Wyoming" },
    { code: "DC", name: "District of Columbia" },
    { code: "PR", name: "Puerto Rico" },
  ],

  // United Kingdom
  GB: [
    { code: "ENG", name: "England" },
    { code: "SCT", name: "Scotland" },
    { code: "WLS", name: "Wales" },
    { code: "NIR", name: "Northern Ireland" },
  ],

  // Germany (16 Bundesländer)
  DE: [
    { code: "BW", name: "Baden-Württemberg" },
    { code: "BY", name: "Bayern (Bavaria)" },
    { code: "BE", name: "Berlin" },
    { code: "BB", name: "Brandenburg" },
    { code: "HB", name: "Bremen" },
    { code: "HH", name: "Hamburg" },
    { code: "HE", name: "Hessen (Hesse)" },
    { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Niedersachsen (Lower Saxony)" },
    { code: "NW", name: "Nordrhein-Westfalen" },
    { code: "RP", name: "Rheinland-Pfalz" },
    { code: "SL", name: "Saarland" },
    { code: "SN", name: "Sachsen (Saxony)" },
    { code: "ST", name: "Sachsen-Anhalt" },
    { code: "SH", name: "Schleswig-Holstein" },
    { code: "TH", name: "Thüringen (Thuringia)" },
  ],

  // France (18 Régions)
  FR: [
    { code: "IDF", name: "Île-de-France (Paris)" },
    { code: "ARA", name: "Auvergne-Rhône-Alpes" },
    { code: "BFC", name: "Bourgogne-Franche-Comté" },
    { code: "BRE", name: "Bretagne (Brittany)" },
    { code: "CVL", name: "Centre-Val de Loire" },
    { code: "COR", name: "Corse (Corsica)" },
    { code: "GES", name: "Grand Est" },
    { code: "HDF", name: "Hauts-de-France" },
    { code: "NOR", name: "Normandie (Normandy)" },
    { code: "NAQ", name: "Nouvelle-Aquitaine" },
    { code: "OCC", name: "Occitanie" },
    { code: "PDL", name: "Pays de la Loire" },
    { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
  ],

  // Italy (20 Regioni)
  IT: [
    { code: "ABR", name: "Abruzzo" },
    { code: "BAS", name: "Basilicata" },
    { code: "CAL", name: "Calabria" },
    { code: "CAM", name: "Campania" },
    { code: "EMR", name: "Emilia-Romagna" },
    { code: "FVG", name: "Friuli Venezia Giulia" },
    { code: "LAZ", name: "Lazio (Rome)" },
    { code: "LIG", name: "Liguria" },
    { code: "LOM", name: "Lombardia (Milan)" },
    { code: "MAR", name: "Marche" },
    { code: "MOL", name: "Molise" },
    { code: "PMN", name: "Piemonte (Turin)" },
    { code: "PUG", name: "Puglia" },
    { code: "SAR", name: "Sardegna" },
    { code: "SIC", name: "Sicilia" },
    { code: "TOS", name: "Toscana (Florence)" },
    { code: "TAA", name: "Trentino-Alto Adige" },
    { code: "UMB", name: "Umbria" },
    { code: "VDA", name: "Valle d'Aosta" },
    { code: "VEN", name: "Veneto (Venice)" },
  ],

  // Spain (17 Comunidades Autónomas)
  ES: [
    { code: "AN", name: "Andalucía" },
    { code: "AR", name: "Aragón" },
    { code: "AS", name: "Asturias" },
    { code: "IB", name: "Illes Balears (Balearic Islands)" },
    { code: "CN", name: "Canarias (Canary Islands)" },
    { code: "CB", name: "Cantabria" },
    { code: "CL", name: "Castilla y León" },
    { code: "CM", name: "Castilla-La Mancha" },
    { code: "CT", name: "Catalunya (Barcelona)" },
    { code: "EX", name: "Extremadura" },
    { code: "GA", name: "Galicia" },
    { code: "MD", name: "Comunidad de Madrid" },
    { code: "MC", name: "Región de Murcia" },
    { code: "NC", name: "Navarra" },
    { code: "PV", name: "País Vasco (Basque Country)" },
    { code: "RI", name: "La Rioja" },
    { code: "VC", name: "Comunitat Valenciana" },
  ],

  // Netherlands (12 Provincies)
  NL: [
    { code: "DR", name: "Drenthe" },
    { code: "FL", name: "Flevoland" },
    { code: "FR", name: "Fryslân (Friesland)" },
    { code: "GE", name: "Gelderland" },
    { code: "GR", name: "Groningen" },
    { code: "LI", name: "Limburg" },
    { code: "NB", name: "Noord-Brabant" },
    { code: "NH", name: "Noord-Holland (Amsterdam)" },
    { code: "OV", name: "Overijssel" },
    { code: "UT", name: "Utrecht" },
    { code: "ZE", name: "Zeeland" },
    { code: "ZH", name: "Zuid-Holland (Rotterdam / The Hague)" },
  ],

  // Ireland (Counties)
  IE: [
    { code: "D", name: "Co. Dublin" },
    { code: "C", name: "Co. Cork" },
    { code: "G", name: "Co. Galway" },
    { code: "LK", name: "Co. Limerick" },
    { code: "WD", name: "Co. Waterford" },
    { code: "KE", name: "Co. Kildare" },
    { code: "MH", name: "Co. Meath" },
    { code: "WW", name: "Co. Wicklow" },
    { code: "LH", name: "Co. Louth" },
    { code: "CW", name: "Co. Carlow" },
    { code: "KK", name: "Co. Kilkenny" },
    { code: "LS", name: "Co. Laois" },
    { code: "LD", name: "Co. Longford" },
    { code: "OY", name: "Co. Offaly" },
    { code: "WH", name: "Co. Westmeath" },
    { code: "WX", name: "Co. Wexford" },
    { code: "CL", name: "Co. Clare" },
    { code: "KY", name: "Co. Kerry" },
    { code: "TP", name: "Co. Tipperary" },
    { code: "MO", name: "Co. Mayo" },
    { code: "RN", name: "Co. Roscommon" },
    { code: "SO", name: "Co. Sligo" },
    { code: "LM", name: "Co. Leitrim" },
    { code: "CN", name: "Co. Cavan" },
    { code: "DL", name: "Co. Donegal" },
    { code: "MN", name: "Co. Monaghan" },
  ],

  // Austria (9 Bundesländer)
  AT: [
    { code: "W", name: "Wien (Vienna)" },
    { code: "NÖ", name: "Niederösterreich" },
    { code: "OÖ", name: "Oberösterreich" },
    { code: "ST", name: "Steiermark (Styria)" },
    { code: "T", name: "Tirol" },
    { code: "K", name: "Kärnten (Carinthia)" },
    { code: "S", name: "Salzburg" },
    { code: "V", name: "Vorarlberg" },
    { code: "B", name: "Burgenland" },
  ],

  // Belgium (Regions & Provinces)
  BE: [
    { code: "BRU", name: "Brussels-Capital Region" },
    { code: "ANW", name: "Antwerpen (Antwerp)" },
    { code: "WVL", name: "West-Vlaanderen (West Flanders)" },
    { code: "OVL", name: "Oost-Vlaanderen (East Flanders)" },
    { code: "VBR", name: "Vlaams-Brabant (Flemish Brabant)" },
    { code: "LIM", name: "Limburg" },
    { code: "LIE", name: "Liège" },
    { code: "HNT", name: "Hainaut" },
    { code: "NAM", name: "Namur" },
    { code: "WBR", name: "Brabant Wallon" },
    { code: "LUX", name: "Luxembourg (Province)" },
  ],

  // Switzerland (26 Cantons)
  CH: [
    { code: "ZH", name: "Zürich" },
    { code: "BE", name: "Bern" },
    { code: "LU", name: "Luzern" },
    { code: "UR", name: "Uri" },
    { code: "SZ", name: "Schwyz" },
    { code: "OW", name: "Obwalden" },
    { code: "NW", name: "Nidwalden" },
    { code: "GL", name: "Glarus" },
    { code: "ZG", name: "Zug" },
    { code: "FR", name: "Fribourg" },
    { code: "SO", name: "Solothurn" },
    { code: "BS", name: "Basel-Stadt" },
    { code: "BL", name: "Basel-Landschaft" },
    { code: "SH", name: "Schaffhausen" },
    { code: "AR", name: "Appenzell Ausserrhoden" },
    { code: "AI", name: "Appenzell Innerrhoden" },
    { code: "SG", name: "St. Gallen" },
    { code: "GR", name: "Graubünden" },
    { code: "AG", name: "Aargau" },
    { code: "TG", name: "Thurgau" },
    { code: "TI", name: "Ticino" },
    { code: "VD", name: "Vaud (Lausanne)" },
    { code: "VS", name: "Valais" },
    { code: "NE", name: "Neuchâtel" },
    { code: "GE", name: "Genève (Geneva)" },
    { code: "JU", name: "Jura" },
  ],

  // Sweden (21 Län)
  SE: [
    { code: "AB", name: "Stockholms län" },
    { code: "O", name: "Västra Götalands län (Gothenburg)" },
    { code: "M", name: "Skåne län (Malmö)" },
    { code: "C", name: "Uppsala län" },
    { code: "E", name: "Östergötlands län" },
    { code: "F", name: "Jönköpings län" },
    { code: "G", name: "Kronobergs län" },
    { code: "H", name: "Kalmar län" },
    { code: "I", name: "Gotlands län" },
    { code: "K", name: "Blekinge län" },
    { code: "N", name: "Hallands län" },
    { code: "S", name: "Värmlands län" },
    { code: "T", name: "Örebro län" },
    { code: "U", name: "Västmanlands län" },
    { code: "W", name: "Dalarnas län" },
    { code: "X", name: "Gävleborgs län" },
    { code: "Y", name: "Västernorrlands län" },
    { code: "Z", name: "Jämtlands län" },
    { code: "AC", name: "Västerbottens län" },
    { code: "BD", name: "Norrbottens län" },
  ],

  // Norway (15 Fylker)
  NO: [
    { code: "03", name: "Oslo" },
    { code: "11", name: "Rogaland (Stavanger)" },
    { code: "15", name: "Møre og Romsdal" },
    { code: "18", name: "Nordland" },
    { code: "31", name: "Østfold" },
    { code: "32", name: "Akershus" },
    { code: "33", name: "Buskerud" },
    { code: "34", name: "Innlandet" },
    { code: "38", name: "Vestfold" },
    { code: "39", name: "Telemark" },
    { code: "42", name: "Agder" },
    { code: "46", name: "Vestland (Bergen)" },
    { code: "50", name: "Trøndelag (Trondheim)" },
    { code: "55", name: "Troms" },
    { code: "56", name: "Finnmark" },
  ],

  // Denmark (5 Regioner)
  DK: [
    { code: "84", name: "Region Hovedstaden (Copenhagen)" },
    { code: "85", name: "Region Sjælland" },
    { code: "83", name: "Region Syddanmark" },
    { code: "82", name: "Region Midtjylland (Aarhus)" },
    { code: "81", name: "Region Nordjylland (Aalborg)" },
  ],

  // Finland (19 Maakunnat)
  FI: [
    { code: "01", name: "Uusimaa (Helsinki)" },
    { code: "02", name: "Varsinais-Suomi (Turku)" },
    { code: "06", name: "Pirkanmaa (Tampere)" },
    { code: "04", name: "Satakunta" },
    { code: "05", name: "Kanta-Häme" },
    { code: "07", name: "Päijät-Häme" },
    { code: "08", name: "Kymenlaakso" },
    { code: "09", name: "Etelä-Karjala" },
    { code: "10", name: "Etelä-Savo" },
    { code: "11", name: "Pohjois-Savo" },
    { code: "12", name: "Pohjois-Karjala" },
    { code: "13", name: "Keski-Suomi" },
    { code: "14", name: "Etelä-Pohjanmaa" },
    { code: "15", name: "Pohjanmaa" },
    { code: "16", name: "Keski-Pohjanmaa" },
    { code: "17", name: "Pohjois-Pohjanmaa (Oulu)" },
    { code: "18", name: "Kainuu" },
    { code: "19", name: "Lappi (Lapland)" },
    { code: "03", name: "Åland" },
  ],

  // Poland (16 Województwa)
  PL: [
    { code: "MZ", name: "Mazowieckie (Warsaw)" },
    { code: "MA", name: "Małopolskie (Kraków)" },
    { code: "DS", name: "Dolnośląskie (Wrocław)" },
    { code: "SL", name: "Śląskie (Katowice)" },
    { code: "WP", name: "Wielkopolskie (Poznań)" },
    { code: "PM", name: "Pomorskie (Gdańsk)" },
    { code: "LD", name: "Łódzkie (Łódź)" },
    { code: "KP", name: "Kujawsko-Pomorskie" },
    { code: "LU", name: "Lubelskie" },
    { code: "LB", name: "Lubuskie" },
    { code: "OP", name: "Opolskie" },
    { code: "PK", name: "Podkarpackie" },
    { code: "PD", name: "Podlaskie" },
    { code: "SK", name: "Świętokrzyskie" },
    { code: "WN", name: "Warmińsko-Mazurskie" },
    { code: "ZP", name: "Zachodniopomorskie (Szczecin)" },
  ],

  // Portugal (18 Distritos & 2 Regiões Autónomas)
  PT: [
    { code: "LI", name: "Lisboa (Lisbon)" },
    { code: "PO", name: "Porto" },
    { code: "BR", name: "Braga" },
    { code: "SE", name: "Setúbal" },
    { code: "AV", name: "Aveiro" },
    { code: "CO", name: "Coimbra" },
    { code: "FA", name: "Faro (Algarve)" },
    { code: "LE", name: "Leiria" },
    { code: "SA", name: "Santarém" },
    { code: "VI", name: "Viseu" },
    { code: "VC", name: "Viana do Castelo" },
    { code: "VR", name: "Vila Real" },
    { code: "CB", name: "Castelo Branco" },
    { code: "EV", name: "Évora" },
    { code: "GU", name: "Guarda" },
    { code: "BE", name: "Beja" },
    { code: "BG", name: "Bragança" },
    { code: "PA", name: "Portalegre" },
    { code: "MA", name: "Madeira" },
    { code: "AC", name: "Açores (Azores)" },
  ],

  // Czech Republic (14 Kraje)
  CZ: [
    { code: "PR", name: "Hlavní město Praha (Prague)" },
    { code: "JM", name: "Jihomoravský kraj (Brno)" },
    { code: "MO", name: "Moravskoslezský kraj (Ostrava)" },
    { code: "ST", name: "Středočeský kraj" },
    { code: "PL", name: "Plzeňský kraj" },
    { code: "JC", name: "Jihočeský kraj" },
    { code: "US", name: "Ústecký kraj" },
    { code: "OL", name: "Olomoucký kraj" },
    { code: "ZL", name: "Zlínský kraj" },
    { code: "KR", name: "Královéhradecký kraj" },
    { code: "PA", name: "Pardubický kraj" },
    { code: "VY", name: "Kraj Vysočina" },
    { code: "LI", name: "Liberecký kraj" },
    { code: "KA", name: "Karlovarský kraj" },
  ],

  // Greece (13 Perifereies)
  GR: [
    { code: "I", name: "Attiki (Athens)" },
    { code: "B", name: "Central Macedonia (Thessaloniki)" },
    { code: "M", name: "Crete" },
    { code: "G", name: "Western Greece" },
    { code: "E", name: "Thessaly" },
    { code: "J", name: "Peloponnese" },
    { code: "H", name: "Central Greece" },
    { code: "A", name: "Eastern Macedonia and Thrace" },
    { code: "D", name: "Epirus" },
    { code: "L", name: "South Aegean" },
    { code: "F", name: "Ionian Islands" },
    { code: "K", name: "North Aegean" },
    { code: "C", name: "Western Macedonia" },
  ],

  // Hungary (19 Megyék + Budapest)
  HU: [
    { code: "BU", name: "Budapest" },
    { code: "PE", name: "Pest" },
    { code: "BA", name: "Baranya (Pécs)" },
    { code: "BZ", name: "Borsod-Abaúj-Zemplén (Miskolc)" },
    { code: "CS", name: "Csongrád-Csanád (Szeged)" },
    { code: "FE", name: "Fejér (Székesfehérvár)" },
    { code: "GY", name: "Győr-Moson-Sopron (Győr)" },
    { code: "HB", name: "Hajdú-Bihar (Debrecen)" },
    { code: "HE", name: "Heves" },
    { code: "JN", name: "Jász-Nagykun-Szolnok" },
    { code: "KE", name: "Komárom-Esztergom" },
    { code: "NO", name: "Nógrád" },
    { code: "SO", name: "Somogy" },
    { code: "SZ", name: "Szabolcs-Szatmár-Bereg" },
    { code: "TO", name: "Tolna" },
    { code: "VA", name: "Vas" },
    { code: "VE", name: "Veszprém" },
    { code: "ZA", name: "Zala" },
  ],

  // Romania (41 Județe + București)
  RO: [
    { code: "B", name: "București" },
    { code: "CJ", name: "Cluj" },
    { code: "TM", name: "Timiș" },
    { code: "IS", name: "Iași" },
    { code: "CT", name: "Constanța" },
    { code: "BV", name: "Brașov" },
    { code: "SB", name: "Sibiu" },
    { code: "PH", name: "Prahova" },
    { code: "AR", name: "Arad" },
    { code: "BC", name: "Bacău" },
    { code: "BH", name: "Bihor" },
    { code: "BN", name: "Bistrița-Năsăud" },
    { code: "BT", name: "Botoșani" },
    { code: "BR", name: "Brăila" },
    { code: "BZ", name: "Buzău" },
    { code: "CS", name: "Caraș-Severin" },
    { code: "CL", name: "Călărași" },
    { code: "CV", name: "Covasna" },
    { code: "DB", name: "Dâmbovița" },
    { code: "DJ", name: "Dolj" },
    { code: "GL", name: "Galați" },
    { code: "GR", name: "Giurgiu" },
    { code: "GJ", name: "Gorj" },
    { code: "HR", name: "Harghita" },
    { code: "HD", name: "Hunedoara" },
    { code: "IL", name: "Ialomița" },
    { code: "MM", name: "Maramureș" },
    { code: "MH", name: "Mehedinți" },
    { code: "MS", name: "Mureș" },
    { code: "NT", name: "Neamț" },
    { code: "OT", name: "Olt" },
    { code: "SM", name: "Satu Mare" },
    { code: "SJ", name: "Sălaj" },
    { code: "SV", name: "Suceava" },
    { code: "TR", name: "Teleorman" },
    { code: "TL", name: "Tulcea" },
    { code: "VS", name: "Vaslui" },
    { code: "VL", name: "Vâlcea" },
    { code: "VN", name: "Vrancea" },
    { code: "IF", name: "Ilfov" },
  ],

  // Croatia (21 Županije)
  HR: [
    { code: "21", name: "Grad Zagreb" },
    { code: "17", name: "Splitsko-dalmatinska (Split)" },
    { code: "08", name: "Primorsko-goranska (Rijeka)" },
    { code: "14", name: "Osječko-baranjska (Osijek)" },
    { code: "18", name: "Istarska (Pula)" },
    { code: "19", name: "Dubrovačko-neretvanska (Dubrovnik)" },
    { code: "13", name: "Zadarska (Zadar)" },
    { code: "01", name: "Zagrebačka" },
    { code: "02", name: "Krapinsko-zagorska" },
    { code: "03", name: "Sisačko-moslavačka" },
    { code: "04", name: "Karlovačka" },
    { code: "05", name: "Varaždinska" },
    { code: "06", name: "Koprivničko-križevačka" },
    { code: "07", name: "Bjelovarsko-bilogorska" },
    { code: "09", name: "Ličko-senjska" },
    { code: "10", name: "Virovitičko-podravska" },
    { code: "11", name: "Požeško-slavonska" },
    { code: "12", name: "Brodsko-posavska" },
    { code: "15", name: "Šibensko-kninska" },
    { code: "16", name: "Vukovarsko-srijemska" },
    { code: "20", name: "Međimurska" },
  ],

  // Bulgaria (Oblasti)
  BG: [
    { code: "22", name: "Sofia (Capital)" },
    { code: "16", name: "Plovdiv" },
    { code: "03", name: "Varna" },
    { code: "02", name: "Burgas" },
    { code: "17", name: "Ruse" },
    { code: "24", name: "Stara Zagora" },
    { code: "04", name: "Veliko Tarnovo" },
    { code: "15", name: "Pleven" },
    { code: "01", name: "Blagoevgrad" },
  ],

  // Slovakia (8 Kraje)
  SK: [
    { code: "BL", name: "Bratislavský kraj (Bratislava)" },
    { code: "KI", name: "Košický kraj (Košice)" },
    { code: "PV", name: "Prešovský kraj" },
    { code: "ZI", name: "Žilinský kraj" },
    { code: "NI", name: "Nitriansky kraj" },
    { code: "BC", name: "Banskobystrický kraj" },
    { code: "TA", name: "Trnavský kraj" },
    { code: "TC", name: "Trenčiansky kraj" },
  ],

  // Slovenia (Statistical Regions)
  SI: [
    { code: "LJ", name: "Osrednjeslovenska (Ljubljana)" },
    { code: "MB", name: "Podravska (Maribor)" },
    { code: "CE", name: "Savinjska (Celje)" },
    { code: "KR", name: "Gorenjska (Kranj)" },
    { code: "KP", name: "Obalno-kraška (Koper)" },
    { code: "GO", name: "Goriška (Nova Gorica)" },
    { code: "NM", name: "Jugovzhodna Slovenija (Novo Mesto)" },
    { code: "MS", name: "Pomurska" },
    { code: "SG", name: "Koroška" },
  ],

  // Estonia (Maakonnad)
  EE: [
    { code: "37", name: "Harjumaa (Tallinn)" },
    { code: "78", name: "Tartumaa (Tartu)" },
    { code: "44", name: "Ida-Virumaa (Narva)" },
    { code: "67", name: "Pärnumaa (Pärnu)" },
    { code: "74", name: "Saaremaa" },
  ],

  // Latvia (Regions)
  LV: [
    { code: "RIX", name: "Rīga" },
    { code: "R", name: "Rīgas reģions" },
    { code: "K", name: "Kurzeme (Liepāja / Ventspils)" },
    { code: "Z", name: "Zemgale (Jelgava)" },
    { code: "V", name: "Vidzeme" },
    { code: "L", name: "Latgale (Daugavpils)" },
  ],

  // Lithuania (Apskritys)
  LT: [
    { code: "VL", name: "Vilniaus apskritis (Vilnius)" },
    { code: "KN", name: "Kauno apskritis (Kaunas)" },
    { code: "KL", name: "Klaipėdos apskritis (Klaipėda)" },
    { code: "SA", name: "Šiaulių apskritis (Šiauliai)" },
    { code: "PN", name: "Panevėžio apskritis (Panevėžys)" },
    { code: "AL", name: "Alytaus apskritis" },
  ],

  // Luxembourg (Cantons)
  LU: [
    { code: "LUX", name: "Luxembourg" },
    { code: "ESC", name: "Esch-sur-Alzette" },
    { code: "DIE", name: "Diekirch" },
  ],

  // Cyprus (Districts)
  CY: [
    { code: "01", name: "Nicosia" },
    { code: "02", name: "Limassol" },
    { code: "03", name: "Larnaca" },
    { code: "04", name: "Paphos" },
    { code: "05", name: "Famagusta" },
  ],

  // Malta (Regions)
  MT: [
    { code: "C", name: "Central Region" },
    { code: "N", name: "Northern Region" },
    { code: "S", name: "Southern Region" },
    { code: "SE", name: "South Eastern Region" },
    { code: "G", name: "Gozo" },
  ],

  // Iceland (Regions)
  IS: [
    { code: "1", name: "Höfuðborgarsvæði (Reykjavík Area)" },
    { code: "2", name: "Suðurnes (Keflavík)" },
    { code: "3", name: "Vesturland" },
    { code: "4", name: "Vestfirðir" },
    { code: "5", name: "Norðurland vestra" },
    { code: "6", name: "Norðurland eystra (Akureyri)" },
    { code: "7", name: "Austurland" },
    { code: "8", name: "Suðurland" },
  ],

  // Liechtenstein (Gemeinden)
  LI: [
    { code: "VAD", name: "Vaduz" },
    { code: "SCH", name: "Schaan" },
    { code: "BAL", name: "Balzers" },
    { code: "TRI", name: "Triesen" },
    { code: "ESC", name: "Eschen" },
    { code: "MAU", name: "Mauren" },
    { code: "RUG", name: "Ruggell" },
  ],
};

export const getSubdivisionsForCountry = (countryCode: string): CountrySubdivision[] => {
  const code = (countryCode || "US").toUpperCase().trim();
  return COUNTRY_SUBDIVISIONS[code] || [];
};
